# Snowshoe hares at Bonanza Creeek

This discussion section will guide you through exploring data about snowshoe hares (Lepus americanus) in the Bonanza Creek Experimental Forest located in Alaska, USA.

- Practice markdown syntax for creating tables and inserting images
- Practice detecting and cleaning messy data
- Use groupby() to calculate summary statistics by groups
- Select, clean, and comment your code to create a condensed data analysis workflow

# Data

We will use data about Snowshoe hares (Lepus americanus) in the Bonanza Creek Experimental Forest [1].

This dataset is stored in the [Environmental Data Initiative (EDI) data repository](https://portal.edirepository.org/nis/mapbrowse?packageid=knb-lter-bnz.55.22). This is a huge data repository committed to making data Findable, Accessible, Interoperable, and Reusable (FAIR). It is the main repository for all the data associated with the Long Term Ecological Research Network (LTER).

Who assembled this data, and why?
A capture-recapture study was conducted by Kiellant et al., to quantify hare population density in Alaska.

What does a single row in the data represent?
A row contains observation data of a single hare.

When and where were the observations collected?
Observations were collected in Tanana Valley, Alaska from 1999 to 2002.

Does the dataset contain sensitive data?
No.

What study protocols were used to collect the data?
Capture-recapture protocal.

What are the units for the hares’ weight?
Grams

Does the metadata say how missing data is encoded?
NaN

Is there a publication associated with this dataset?
Flora, B.K. 2002. Comparison of snowshoe hare populations in Interior. M.S. Thesis. University of Alaska Fairbanks. Fairbanks, AK, USA.

Citation
Kielland, K., F.S. Chapin, R.W. Ruess, and Bonanza Creek LTER. 2017. Snowshoe hare physical data in Bonanza Creek Experimental Forest: 1999-Present ver 22. Environmental Data Initiative. https://doi.org/10.6073/pasta/03dce4856d79b91557d8e6ce2cbcdc14 (Accessed 2026-10-15).

*Possible Issues*
In the dataset 24.2% of the cells have missing data, would this skew results?

How are recaptured hares dealth with in the analysis?

Do you need to add an attribution in the image description? 
Image is license under  Creative Commons CC0 1.0 Universal Public Domain Dedication which does not require attribution.

![Snowshoe Hare](https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg/960px-SNOWSHOE_HARE_%28Lepus_americanus%29_%285-28-2015%29_quoddy_head%2C_washington_co%2C_maine_-01_%2818988734889%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=thumbnail&_=20170313021652)

In [11]:
import pandas as pd

hare = pd.read_csv("data/55_Hare_Data_2012.txt")

In [13]:
hare.shape

(3380, 14)

In [2]:
hare.head(3)

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
0,11/26/1998,NaN,bonrip,1A,414D096A08,NaN,NaN,NaN,1370.0,160.0,NaN,917.0,51,Population
1,11/26/1998,NaN,bonrip,2C,414D320671,NaN,M,NaN,1430.0,NaN,NaN,936.0,51,Population
2,11/26/1998,NaN,bonrip,2D,414D103E3A,NaN,M,NaN,1430.0,NaN,NaN,921.0,51,Population

In [3]:
hare.tail(3)

,date,time,grid,trap,l_ear,r_ear,sex,age,weight,hindft,notes,b_key,session_id,study
3377,8/7/2002,NaN,bonrip,4b,1217,1218,NaN,NaN,1000.0,134.0,NaN,69.0,64,Population
3378,8/8/2002,NaN,bonrip,6d,1217,1218,NaN,NaN,990.0,NaN,NaN,69.0,64,Population
3379,8/6/2002,NaN,bonrip,4b,1058,1060,M,NaN,1460.0,119.0,NaN,32.0,64,Population

In [6]:
hare.dtypes

date           object
time           object
grid           object
trap           object
l_ear          object
r_ear          object
sex            object
age            object
weight        float64
hindft        float64
notes          object
b_key         float64
session_id      int64
study          object
dtype: object

In [9]:
hare.nunique()

date           256
time           165
grid             5
trap           121
l_ear         1020
r_ear          963
sex             12
age             30
weight         266
hindft          90
notes          118
b_key         1026
session_id     113
study            4
dtype: int64

In [10]:
hare.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3380 entries, 0 to 3379
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        3380 non-null   object
 1   time        264 non-null    object
 2   grid        3380 non-null   object
 3   trap        3368 non-null   object
 4   l_ear       3332 non-null   object
 5   r_ear       3211 non-null   object
 6   sex         3028 non-null   object
 7   age         1269 non-null   object
 8   weight      2845 non-null   float64
 9   hindft      1633 non-null   float64
 10  notes       243 non-null    object
 11  b_key       3333 non-null   float64
 12  session_id  3380 non-null   int64
 13  study       3217 non-null   object
dtypes: float64(3), int64(1), object(10)
memory usage: 369.8+ KB

In [16]:
hare['hindft'].describe()

count    1633.000000
mean      130.872627
std        16.155295
min        60.000000
25%       128.000000
50%       135.000000
75%       140.000000
max       160.000000
Name: hindft, dtype: float64

In [17]:
hare['weight'].describe()

count    2845.000000
mean     1346.081547
std       345.160112
min         0.000000
25%      1180.000000
50%      1400.000000
75%      1580.000000
max      2365.000000
Name: weight, dtype: float64

In [24]:
hare.isna().sum()

date             0
time          3116
grid             0
trap            12
l_ear           48
r_ear          169
sex            352
age           2111
weight         535
hindft        1747
notes         3137
b_key           47
session_id       0
study          163
dtype: int64